# Generated by Django 5.1 on 2024-08-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roaming_files', '0002_rename_file_roamingin_input_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roamingout',
            name='input_file',
            field=models.FileField(null=True, upload_to='roaming_out_files/inputs'),
        ),
        migrations.AlterField(
            model_name='roamingout',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='roaming_out_files/outputs'),
        ),
    ]
