# Generated by Django 5.1 on 2024-08-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roaming_files', '0003_alter_roamingout_input_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roamingin',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='roaming_in_files/outputs'),
        ),
        migrations.AlterField(
            model_name='roamingin',
            name='input_file',
            field=models.FileField(null=True, upload_to='roaming_in_files/inputs'),
        ),
    ]
